services:
  # Backend API service
  - type: web
    name: apple-certificate-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DROPBOX_APP_KEY
        value: 2bi422xpd3xd962
      - key: DROPBOX_APP_SECRET
        value: j3yx0b41qdvfu86
      - key: DROPBOX_REFRESH_TOKEN
        value: RvyL03RE5qAAAAAAAAAAAVMVebvE7jDx8Okd0ploMzr85c6txvCRXpJAt30mxrKF
      - key: PORT
        value: 10000

  # Frontend web service
  - type: web
    name: apple-certificate-store
    runtime: node
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist -l $PORT
    envVars:
      - key: VITE_API_URL
        fromService:
          name: apple-certificate-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL